export const MOBILE_STORAGE_KEYS = {
  accessToken: 'authToken',
  refreshToken: 'refreshToken',
  user: 'user',
  pendingVerificationEmail: 'pendingVerificationEmail',
  selectedAddress: 'selectedAddress',
  persistedState: 'app_state',
} as const;

export const MOBILE_ROUTE_SEGMENTS = {
  login: 'login',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  dashboard: 'dashboard',
  delivery: 'delivery',
  orderHistory: 'order-history',
  verifyEmail: 'verify-email',
  register: 'register',
  profile: 'profile',
  cart: 'cart',
  checkout: 'checkout',
  address: 'address',
  paymentHistory: 'payment-history',
} as const;

export const MOBILE_ROUTES = {
  login: `/${MOBILE_ROUTE_SEGMENTS.login}`,
  forgotPassword: `/${MOBILE_ROUTE_SEGMENTS.forgotPassword}`,
  resetPassword: `/${MOBILE_ROUTE_SEGMENTS.resetPassword}`,
  dashboard: `/${MOBILE_ROUTE_SEGMENTS.dashboard}`,
  delivery: `/${MOBILE_ROUTE_SEGMENTS.delivery}`,
  orderHistory: `/${MOBILE_ROUTE_SEGMENTS.orderHistory}`,
  verifyEmail: `/${MOBILE_ROUTE_SEGMENTS.verifyEmail}`,
} as const;

export const MOBILE_API_ENDPOINTS = {
  auth: {
    login: 'auth/login',
    register: 'auth/register',
    logout: 'auth/logout',
    refreshToken: 'auth/refresh-token',
    sendOtp: 'auth/send-otp',
    verifyOtp: 'auth/verify-otp',
    forgotPassword: 'auth/forgot-password',
    resetPassword: 'auth/reset-password',
  },
  addresses: {
    list: 'addresses',
    byId: (addressId: string | undefined) => `addresses/${addressId}`,
    update: (addressId: string | undefined) => `addresses/${addressId}`,
  },
  products: {
    list: (page: number, limit: number) => `products?page=${page}&limit=${limit}`,
  },
  categories: 'categories',
  orders: {
    list: 'orders',
    create: 'orders',
    cancel: (orderId: string) => `orders/${orderId}/cancel`,
    track: (orderId: string) => `orders/${orderId}/track`,
  },
  delivery: {
    orders: (status: 'available' | 'assigned') => `delivery/orders?status=${status}`,
    updateOrder: (orderId: string, action: string) => `delivery/orders/${orderId}/${action}`,
    location: 'delivery/location',
  },
  payments: {
    transactions: (limit: number) => `payments/transactions?limit=${limit}`,
    createOrder: 'payments/razorpay/create-order',
    verifyOrder: 'payments/razorpay/verify',
  },
} as const;

export const MOBILE_CONFIG = {
  minimumPasswordLength: 8,
  otpLength: 6,
  otpExpirySeconds: 5 * 60,
  otpTimerIntervalMs: 1_000,
  verifiedRedirectDelayMs: 2_000,
  backPressExitWindowMs: 2_000,
  productsPageSize: 20,
  transactionPageSize: 100,
  orderTrackingIntervalMs: 15_000,
  currency: 'INR',
  minorCurrencyUnitsPerMajor: 100,
} as const;

export const MOBILE_APP_TEXT = {
  name: 'Softiqo',
  description: 'Fresh groceries, delivered fast',
  login: {
    title: 'Sign in',
    email: 'Email',
    emailRequired: 'Email is required',
    invalidEmail: 'Please enter a valid email',
    password: 'Password',
    passwordRequired: 'Password is required',
    minimumPassword: 'Password must be at least 6 characters',
    emailPlaceholder: 'demo@email.com',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember Me',
    forgotPassword: 'Forgot Password?',
    loggingIn: 'Logging in...',
    signIn: 'Login',
    noAccount: "Don't have an Account ?",
    signUp: 'Sign up',
    requiredFields: 'Please fill all fields correctly',
  },
  registration: {
    title: 'Sign Up',
    name: 'Name',
    namePlaceholder: 'John Doe',
    nameRequired: 'Name is required',
    nameMinimum: 'Name must be at least 2 characters',
    email: 'Email',
    emailRequired: 'Email is required',
    invalidEmail: 'Please enter a valid email',
    emailPlaceholder: 'demo@email.com',
    phone: 'Phone',
    phonePlaceholder: 'Enter your phone number',
    phoneRequired: 'Phone is required',
    phoneMinimum: 'Phone must be at least 10 digits',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    passwordRequired: 'Password is required',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    confirmPasswordRequired: 'Please confirm your password',
    passwordsMismatch: 'Passwords do not match',
    terms: 'I agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    termsRequired: 'You must agree to the terms',
    creatingAccount: 'Creating Account...',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    requiredFields: 'Please fill all fields correctly',
  },
  verification: {
    title: 'Verify Email',
    heading: 'Verify Your Email',
    codeSentPrefix: "We've sent a",
    codeSentSuffix: '-digit code to',
    developmentCode: 'Development verification code:',
    enterCode: 'Enter OTP Code',
    required: 'OTP is required',
    invalidCode: 'OTP must be {{length}} digits',
    expiresIn: 'Code expires in:',
    verify: 'Verify Email',
    verifying: 'Verifying...',
    verified: 'Verified',
    didNotReceive: "Didn't receive the code?",
    resend: 'Resend OTP',
    wait: 'Wait for timer to expire',
    invalidCodeEntry: 'Please enter a valid {{length}}-digit OTP',
    success: 'Email verified successfully!',
  },
  recovery: {
    backToSignIn: 'Back to sign in',
    security: 'ACCOUNT SECURITY',
    choosePassword: 'Choose a new password',
    resetDescription: 'Use at least {{length}} characters. This reset link can only be used once.',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updating: 'Updating...',
    updatePassword: 'Update password',
    returnToSignIn: 'Return to sign in',
    accountRecovery: 'ACCOUNT RECOVERY',
    forgotPassword: 'Forgot your password?',
    requestDescription: 'Enter your account email. If it matches, we’ll send a secure reset link.',
    email: 'Email address',
    openDevelopmentLink: 'Open development reset link',
    sending: 'Sending...',
    sendResetLink: 'Send reset link',
    emailRequired: 'Enter the email address on your account.',
    passwordMinimum: 'Use at least {{length}} characters for your new password.',
    passwordsMismatch: 'The passwords do not match.',
    passwordUpdated: 'Password updated. Sign in with your new password.',
    requestFallback: 'If an account exists, a reset link has been sent.',
    requestFailed: 'Unable to request a password reset.',
    invalidLink: 'This reset link is invalid or expired.',
  },
  address: {
    types: [
      { value: 'home', label: 'Home' },
      { value: 'work', label: 'Work' },
      { value: 'other', label: 'Other' },
    ],
    savedAddresses: 'Saved Addresses',
    noAddresses: 'No saved addresses yet. Tap + to add your first address.',
    addAddress: 'Add new address',
    searchLocation: 'Search location',
    completeAddress: 'Complete Address',
    houseNumber: 'House / Flat No.',
    city: 'City',
    addressType: 'Address Type',
    updateAddress: 'Update Address',
    saveAddress: 'Save Address',
    fetchError: 'Unable to load addresses.',
  },
  dashboard: {
    deliveringTo: 'Delivering to',
    search: 'Search...',
    loadingProducts: 'Loading more products...',
    itemsAdded: '{{count}} items added',
    readyToCheckout: 'Ready to checkout',
    viewCart: 'View Cart',
  },
  product: { off: '% OFF', add: 'ADD' },
  cart: {
    title: 'Shopping Cart',
    summary: 'Order Summary',
    quantity: 'Qty: {{count}}',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    gst: 'GST (5%)',
    total: 'Total',
    terms: 'By placing order, you agree to our Terms & Conditions',
    deliveringTo: 'Delivering To',
    checkout: 'Checkout',
    empty: 'Your cart is empty. Add fresh groceries to continue.',
  },
  checkout: {
    title: 'Checkout',
    confirmed: 'Order confirmed',
    continueShopping: 'Continue shopping',
    empty: 'Your cart is empty.',
    browseProducts: 'Browse products',
    deliveryAddress: 'Delivery address',
    manage: 'Manage',
    addSavedAddress: 'Add a saved address before placing your order.',
    addAddress: 'Add address',
    instructions: 'Delivery instructions (optional)',
    instructionsPlaceholder: 'Gate code, drop-off details',
    paymentMethod: 'Payment method',
    card: 'Credit or debit card',
    upi: 'UPI',
    wallet: 'Wallet or net banking',
    cod: 'Cash on delivery',
    summary: 'Order summary',
    quantity: 'Qty: {{count}}',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    free: 'Free',
    total: 'Total',
    processing: 'Processing…',
    placeOrder: 'Place order',
    cartEmpty: 'Your cart is empty.',
    chooseAddress: 'Choose or add a delivery address to continue.',
  },
  orders: {
    account: 'ACCOUNT',
    title: 'Your orders',
    refresh: 'Refresh',
    loading: 'Loading your orders…',
    quantity: 'Qty {{count}}',
    track: 'Track order',
    payNow: 'Pay now',
    cancel: 'Cancel',
    estimated: 'Estimated {{date}}',
    callDeliveryPartner: 'Call delivery partner',
    autoRefresh: 'Status refreshes automatically.',
    emptyTitle: 'No orders yet',
    emptyDescription: 'Your completed checkouts will appear here.',
  },
  payments: {
    account: 'ACCOUNT',
    title: 'Payment history',
    loading: 'Loading payment activity…',
    payment: 'Payment',
    reference: 'Reference:',
    emptyTitle: 'No payment activity',
    emptyDescription: 'Payments and refunds will appear here.',
    showing: 'Showing the latest {{shown}} of {{total}} transactions',
  },
  delivery: {
    role: 'DELIVERY PARTNER',
    title: 'Delivery queue',
    updateLocation: 'Update location',
    available: 'Available orders',
    callCustomer: 'Call customer',
    itemCount: '{{count}} items · {{method}}',
    accept: 'Accept delivery',
    noAvailable: 'No orders are ready for delivery.',
    assigned: 'Assigned to me',
    itemCountShort: '{{count}} items',
    markPickedUp: 'Mark picked up',
    markDelivered: 'Mark delivered',
    noAssigned: 'You have no assigned deliveries.',
    signOut: 'Sign out',
  },
  profile: {
    title: 'My Profile',
    yourOrders: 'Your Orders',
    helpSupport: 'Help & Support',
    wishlist: 'Your Wishlist',
    information: 'Your Information',
    savedAddresses: 'Saved Addresses',
    manageAddresses: 'Manage delivery addresses',
    paymentHistory: 'Payment history',
    giftCards: 'E-Gift Cards',
    signOut: 'Sign out',
  },
  errors: {
    unableRequest: 'Unable to complete the request.',
    unableCheckout: 'Unable to complete checkout.',
    backAgainToExit: 'Press back again to exit',
    validFields: 'Please fill all fields correctly',
    validOtp: 'Please enter a valid {{length}}-digit OTP',
    locationUnavailable: 'Location is unavailable. Check this device’s location permission.',
    loginFailed: 'Login failed.',
    unableSignIn: 'Unable to sign in. Please try again.',
    registrationFailed: 'Registration failed.',
    unableCreateAccount: 'Unable to create your account. Please try again.',
    verificationFailed: 'Email verification failed.',
    unableVerifyEmail: 'Unable to verify your email. Please try again.',
    unableResendCode: 'Unable to resend the code.',
    unableResendCodeRetry: 'Unable to resend the code. Please try again.',
    paymentLoadFailed: 'Payment checkout could not be loaded. Check your internet connection.',
    paymentCancelled: 'Payment cancelled.',
    paymentFailed: 'Payment failed.',
    unablePaymentHistory: 'Unable to load payment history.',
    customerFallback: 'Customer',
    productFallback: 'Product',
    orderFallback: 'Order',
    orderSavedCanPay: 'Your order is saved and can be paid from order history.',
    orderMissing: 'The server did not return an order.',
    paymentVerificationFailed: 'Payment verification failed.',
  },
} as const;
